config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'ideas#index'
  resources :ideas
  get 'about' => 'static_pages#about'
  get 'random' => 'static_pages#random'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/idea.rb
# frozen_string_literal: true

class Idea < ActiveRecord::Base
  validates :description, :author, presence: true
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/ideas_controller.rb
# frozen_string_literal: true

class IdeasController < ApplicationController
  def index
    @ideas = Idea.order('created_at DESC').paginate(page: params[:page], per_page: 3)
  end

  def create
    @ideas = Idea.create(idea_params)
    redirect_to root_path
  end

  def edit
    @idea = Idea.find(params[:id])
  end

  def update
    @idea = Idea.find(params[:id])
    if @idea.update(idea_params)
      redirect_to root_path
    else
      redirect_to edit_idea_path(params[:id])
    end
  end

  def destroy
    @idea = Idea.find(params[:id])
    @idea.destroy
    redirect_to root_path
  end

  private

  def idea_params
    params.require(:idea).permit(:description, :author)
  end
end

app/controllers/static_pages_controller.rb
# frozen_string_literal: true

class StaticPagesController < ApplicationController
  def about; end

  def random
    @idea = Idea.order('RANDOM()').first
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/ideas_helper.rb
# frozen_string_literal: true

module IdeasHelper
end

app/helpers/static_pages_helper.rb
# frozen_string_literal: true

module StaticPagesHelper
end

app/views/ideas/edit.html.erb
<div class = "panel panel-default">
<div class = "panel-body">
<h3 style="color: #7721a2;">Revise Idea</h3>
<%= simple_form_for @idea, method: :patch do |f| %>
<%= f.input :description %>
  <%= f.input :author %>
  <%= f.submit 'Submit', class: 'btn btn-primary' %>
<% end %>
</div>
</div>

app/views/ideas/index.html.erb
<div class = "jumbotron">
<h3 style="color: #7721a2;">Post Your Ideas</h3>
<p class = "er" style="color: #24a696;">Welcome to the first step towards success. We’re excited for you!</p>
</div>


<% @ideas.each do |idea| %>
<div id = "mypanel"
  <div class="panel panel-default">
    <div class="panel-body">
      <blockquote>
        <p><%= idea.description %></p>
        <small>by <%= idea.author %></small>
      </blockquote>
      <br>
      <div class="btn-group" role="group">
        <%= link_to 'Delete', idea_path(idea), method: :delete, class: 'btn btn-sm btn-danger', data: {confirm: "Are you sure?"} %>
        <%= link_to 'Revise', edit_idea_path(idea), class: 'btn btn-sm btn-success' %>
      </div>
    </div>
  </div>

<% end %>

<div class = "text-center">
  <%= will_paginate @ideas %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ideator</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <link href='https://fonts.googleapis.com/css?family=Pacifico' rel='stylesheet' type='text/css'>
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-T8Gy5hrqNKT+hzMclPo118YTQO6cYprQmhrYwIiQ/3axmI1hQomh7Ud2hPOy8SP1" crossorigin="anonymous">
  </head>
  <body>
    <div id = "wrap">
      <nav class="navbar navbar-default">
        <div class="container-fluid">
          <div class = "navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/" style="color: #24a696;">Ideator</a>
          </div>
          <div class="collapse navbar-collapse text-center" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
              <li><%=link_to 'All Ideas',root_path %></li>
              <li><%=link_to 'Inspire Me',random_path %></li>
              <li><%= link_to 'About',about_path %></li>
              <li><button type="button" class="btn btn-primary navbar-btn" data-toggle="modal" data-target="#myModal">Add Idea</button></li>
            </ul>
          </div>
        </div>
      </nav>
      <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
              <h4 class="modal-title" id="myModalLabel">Post your idea</h4>
            </div><!-- modal-header -->
            <%= simple_form_for Idea.new do |f| %>
              <div class="modal-body">
                <%= f.input :description %>
                <%= f.input :author %>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <%= f.submit 'Submit', class: 'btn btn-primary' %>
              </div><!-- modal-footer -->
            <% end %>
          </div><!-- modal-content-->
        </div><!-- modal-dialog-->
      </div><!-- modal fade -->
    </div>
    <div class = "container">
      <%= yield %>
    </div>

    <div id = "footer">
      <footer class= "footer text-center">
        <div class="container">
          <div class = "row">
            <div class = "col-xs-12 col-md-4">
              <h4>Contact</h4>
              <p>shrijanapoudel.com.np</p>
            </div>
            <div class = "col-xs-12 col-md-4">
              <h4>Find Us</h4>
              <div style = "font-size: 40px;">
                <a href = "#"><i class="fa fa-facebook-official social" ></i></a>
                <a href = "#"><i class="fa fa-twitter-square social" ></i></a>
                <a href = "#"><i class="fa fa-linkedin-square social" ></i></a>
              </div>
            </div>
            <div class = "col-xs-12 col-md-4">
              <h4>©shrijana-2016</h4>
              <p>All Rights Reserved</p>
            </div>
          </div>
        </div>
      </footer>
    </div>
  </body>
</html>

app/views/static_pages/about.html.erb
<h1>About</h1>

<h4>Share you ideas with the world and find others.</h4>

<p>
  Ideator can help take your idea and turn it into reality.</p>

<p>
  Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
  consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
  cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
  proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
</p>

<p>
  Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
  consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
  cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
  proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
</p>

app/views/static_pages/random.html.erb
<% if @idea.present? %>
  <%= link_to 'Inspire Me', random_path, class: 'btn btn-primary btn-block' %>
<div class = "panel panel-default">
	<div class = "panel-body">
		<blockquote>
<p><%= @idea.description %></p>
<small><%= @idea.author %></small>
</blockquote>
<br>
<div class="btn-group" role= "group">
	<%= link_to 'Delete',idea_path(@idea),class: 'btn btn-sm btn-danger',data: {confirm: "Are you sure?"} %>
	<%= link_to 'Revise',edit_idea_path(@idea), class: 'btn btn-sm btn-success' %>
</div>
</div>
</div>
<% end %>